Feature/card visuals 6
Al2Klimov/icingaweb2-module-fourcolors pull request #9
Opened 2023-09-01 13:38 UTC by theFeu

2023-09-01 13:38 UTC, theFeu commented
![image](https://github.com/Al2Klimov/icingaweb2-module-fourcolors/assets/22217062/ad9af0da-6e49-44f6-8603-1a07d30f953b)

Added visuals for the cards :)

2023-09-01 13:55 UTC, Al2Klimov requested changes

2023-09-01 13:55 UTC, Al2Klimov commented on public/css/module.less
> +.card-container {
License header missing.

2023-09-01 13:55 UTC, Al2Klimov commented on public/css/module.less
> +}
This is what I call an easter egg.

2023-09-01 13:55 UTC, Al2Klimov commented on public/css/module.less
> +}
\n missing.

2023-09-01 13:55 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +    public function renderHand(Card $card = null) {
Could Card implement ValidHtml instead?

2023-09-01 13:55 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +        $cardColor = 'black';
Could be a switch default:

2023-09-01 13:55 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +        $cardNumber = '';
Could be in _else_

2023-09-01 13:55 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +            $cardNumber = '​';
Isn't this a no-op?

2023-09-01 13:55 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +                Html::tag('p', ['class' => 'card-color ' . $cardColor], $card->color?$card->color:'​'),
_?:_ is nice, but did you know _??_

2023-09-01 13:55 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +        $this->addContent(Html::tag('div', ['class' => 'hand'], $hand));
No array_map anymore?

2023-09-01 13:55 UTC, Al2Klimov commented on public/css/module.less
> +}
Why no Windows logo style division of the color choose card? (Top left, top right, ...)

2023-09-02 07:28 UTC, theFeu commented on application/controllers/PlayController.php
> +                Html::tag('p', ['class' => 'card-color ' . $cardColor], $card->color?$card->color:'​'),
I did not!

2023-09-02 07:29 UTC, theFeu commented on public/css/module.less
> +}
I tried that, but it would render the +4 unreadable, this way we can still have it in the bottom and it's both visually clear what the card does and it's readable :)

2023-09-02 07:32 UTC, theFeu commented on application/controllers/PlayController.php
> +        $this->addContent(Html::tag('div', ['class' => 'hand'], $hand));
I feel like this is more readable than array_map :)

2023-09-02 07:35 UTC, theFeu commented on application/controllers/PlayController.php
> +    public function renderHand(Card $card = null) {
It probably could. But I didn't really figure out how to do that (yet) :)

2023-09-02 07:38 UTC, theFeu commented on application/controllers/PlayController.php
> +            $cardNumber = '​';
?

2023-09-02 07:44 UTC, theFeu commented on application/controllers/PlayController.php
> +                Html::tag('p', ['class' => 'card-color ' . $cardColor], $card->color?$card->color:'​'),
Seeing this now, I am not sure if the zero-width space I put in here got lost - can you show me what a black card looks like in your environment with this branch? :)

2023-09-02 07:45 UTC, theFeu commented on application/controllers/PlayController.php
> +            $cardNumber = '​';
Same as below, the $cardNumber is set to a ZWSP when it's a black card :)

2023-09-04 09:53 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +        $cardNumber = '';
Now it vanished completely.

2023-09-04 09:55 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +            $cardNumber = '​';
In this case please use htmldecodespecialchars() or whatever with explicit Unicode notation.

2023-09-04 09:58 UTC, Al2Klimov commented on public/css/module.less
> +}
Then please could you re-order the colors, so that they're more contrastful to their neighbours?

2023-09-04 09:58 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +    public function renderHand(Card $card = null) {
`class Card implements ValidHtml { ...`

2023-09-04 11:39 UTC, theFeu commented on application/controllers/PlayController.php
> +            $cardNumber = '​';
So according to [this](https://www.compart.com/en/unicode/U+200B), then `htmlspecialchars_decode('&#8203;')` should do the trick, right?
It does not, neither with the other two options given in my source... :(

2023-09-04 13:05 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +            $cardNumber = '​';
Forgot ENT_HTML5?

2023-09-04 13:39 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +            $cardNumber = '​';
Try some more flags and/or hex2bin() instead.

2023-09-04 14:29 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +        $cardNumber = '';
I mean, now there's a case with the variable being not set at all. I just wanted the final ZWSP being in an else, not elseif. OK?

2023-09-04 14:29 UTC, Al2Klimov commented on application/controllers/PlayController.php
> +                Html::tag('p', ['class' => 'card-color ' . $cardColor], $card->color?$card->color:'​'),
https://www.tutorialspoint.com/php7/php7_coalescing_operator.htm

2023-09-04 14:35 UTC, theFeu commented on application/controllers/PlayController.php
> +                Html::tag('p', ['class' => 'card-color ' . $cardColor], $card->color?$card->color:'​'),
But in this case the ?: makes more sense than the ??, does it not?

2025-10-10 14:10 UTC, closed without merging